<?php
return array (
  12 => 
  array (
    'id' => '12',
    'catid' => '30',
    'typeid' => '0',
    'title' => '产品剖析3',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品剖析3',
    'description' => '产品剖析3',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=30&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727288',
    'updatetime' => '1499593148',
    'redirect_url' => '',
    'hitsid' => 'c-1-12',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '30',
    'typeid' => '0',
    'title' => '产品剖析1',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品剖析1',
    'description' => '产品剖析1',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=30&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727237',
    'updatetime' => '1496727270',
    'redirect_url' => '',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '30',
    'typeid' => '0',
    'title' => '产品剖析2',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品剖析2',
    'description' => '产品剖析2',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=30&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727273',
    'updatetime' => '1496727285',
    'redirect_url' => '',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>