<?php
return array (
  16 => 
  array (
    'id' => '16',
    'catid' => '32',
    'typeid' => '0',
    'title' => '米花糖系列',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0606/20170606112436907.png',
    'keywords' => '',
    'description' => '100%食品级配方，安全健康',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=32&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496762708',
    'updatetime' => '1496762819',
    'redirect_url' => '',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '32',
    'typeid' => '0',
    'title' => '棉花糖系列',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0606/20170606112436907.png',
    'keywords' => '',
    'description' => '100%食品级配方，安全健康',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=32&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496763742',
    'updatetime' => '1496763784',
    'redirect_url' => '',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '32',
    'typeid' => '0',
    'title' => '米花糖系列3',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0606/20170606112436907.png',
    'keywords' => '',
    'description' => '100%食品级配方，安全健康',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=32&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496763809',
    'updatetime' => '1496763828',
    'redirect_url' => '',
    'hitsid' => 'c-1-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '36',
    'typeid' => '0',
    'title' => '食品级',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'shipinj',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=36&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496765665',
    'updatetime' => '1496765689',
    'redirect_url' => 'http://www.baidu.com',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '36',
    'typeid' => '0',
    'title' => '食品级2',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'shipjiji',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=36&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496765693',
    'updatetime' => '1496765715',
    'redirect_url' => 'http://www.qq.com',
    'hitsid' => 'c-1-23',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>