<?php
return array (
  13 => 
  array (
    'id' => '13',
    'catid' => '31',
    'typeid' => '0',
    'title' => '营养膳食1',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0605/20170605124814798.jpg',
    'keywords' => '营养膳食1',
    'description' => '营养膳食1',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=31&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727404',
    'updatetime' => '1496727427',
    'redirect_url' => '',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '31',
    'typeid' => '0',
    'title' => '营养膳食2',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0605/20170605124814798.jpg',
    'keywords' => '营养膳食2',
    'description' => '营养膳食2',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=31&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727465',
    'updatetime' => '1496727483',
    'redirect_url' => '',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '31',
    'typeid' => '0',
    'title' => '营养膳食3',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0605/20170605124814798.jpg',
    'keywords' => '营养膳食3',
    'description' => '营养膳食3',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=31&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727486',
    'updatetime' => '1496727503',
    'redirect_url' => '',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>