<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '29',
    'typeid' => '0',
    'title' => '如何瘦身如何手很',
    'style' => '',
    'thumb' => '',
    'keywords' => '健康瘦身1',
    'description' => '健康瘦身1',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=29&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496726934',
    'updatetime' => '1499593134',
    'redirect_url' => '',
    'hitsid' => 'c-1-8',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '30',
    'typeid' => '0',
    'title' => '产品剖析3',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品剖析3',
    'description' => '产品剖析3',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=30&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727288',
    'updatetime' => '1499593148',
    'redirect_url' => '',
    'hitsid' => 'c-1-12',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '29',
    'typeid' => '0',
    'title' => '如何瘦身如何手很',
    'style' => '',
    'thumb' => '',
    'keywords' => '健康瘦身2',
    'description' => '健康瘦身2',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=29&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496726959',
    'updatetime' => '1496726974',
    'redirect_url' => '',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '30',
    'typeid' => '0',
    'title' => '产品剖析1',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品剖析1',
    'description' => '产品剖析1',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=30&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727237',
    'updatetime' => '1496727270',
    'redirect_url' => '',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '30',
    'typeid' => '0',
    'title' => '产品剖析2',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品剖析2',
    'description' => '产品剖析2',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=30&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727273',
    'updatetime' => '1496727285',
    'redirect_url' => '',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '31',
    'typeid' => '0',
    'title' => '营养膳食1',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0605/20170605124814798.jpg',
    'keywords' => '营养膳食1',
    'description' => '营养膳食1',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=31&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727404',
    'updatetime' => '1496727427',
    'redirect_url' => '',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '31',
    'typeid' => '0',
    'title' => '营养膳食2',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0605/20170605124814798.jpg',
    'keywords' => '营养膳食2',
    'description' => '营养膳食2',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=31&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727465',
    'updatetime' => '1496727483',
    'redirect_url' => '',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '31',
    'typeid' => '0',
    'title' => '营养膳食3',
    'style' => '',
    'thumb' => 'http://reafe.itcask.com/uploadfile/2017/0605/20170605124814798.jpg',
    'keywords' => '营养膳食3',
    'description' => '营养膳食3',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=31&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496727486',
    'updatetime' => '1496727503',
    'redirect_url' => '',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>