<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '29',
    'typeid' => '0',
    'title' => '如何瘦身如何手很',
    'style' => '',
    'thumb' => '',
    'keywords' => '健康瘦身1',
    'description' => '健康瘦身1',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=29&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496726934',
    'updatetime' => '1499593134',
    'redirect_url' => '',
    'hitsid' => 'c-1-8',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '29',
    'typeid' => '0',
    'title' => '如何瘦身如何手很',
    'style' => '',
    'thumb' => '',
    'keywords' => '健康瘦身2',
    'description' => '健康瘦身2',
    'posids' => '0',
    'url' => 'http://reafe.itcask.com/index.php?m=content&c=index&a=show&catid=29&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496726959',
    'updatetime' => '1496726974',
    'redirect_url' => '',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>